name: Docker Image Build and run

on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run the Docker container
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHANNEL_LIST: ${{ vars.CHANNEL_LIST }}
        NO_WATCH_URL: ${{ vars.NO_WATCH_URL }}
      run: docker run -e TELEGRAM_CHAT_ID -e TELEGRAM_BOT_TOKEN -e OPENAI_API_KEY -e CHANNEL_LIST -e NO_WATCH_URL stell0/youtubetelegramsummaries:latest
